apiVersion: apps/v1
kind: Deployment
metadata:
  name: goat-cron
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goat-cron
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: goat-cron
    spec:
      containers:
        - image: ${DOCKER_IMAGE}
          imagePullPolicy: IfNotPresent
          name: goat-cron
          envFrom:
            - secretRef:
                name: cron-secrets
          volumeMounts:
            - mountPath: /opt/config/db
              name: cron-goat-secrets
      volumes:
        - name: cron-goat-secrets
          secret:
            secretName: cron-goat-secrets