apiVersion: ENC[AES256_GCM,data:2nc=,iv:qv0TyLX3jJVF1LX0jZHfP2nYKifJUW8RLCCYsScqF3I=,tag:6auuVl8vNlSWBaabS1JBHA==,type:str]
kind: ENC[AES256_GCM,data:sdK/HJlL,iv:MmRWfmAQogZB8az3D5pzWNkAVfh24OEhNQYtyrQ/rfA=,tag:JqKJBqTLtpwbuPlUTRSaPg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XJs9AQrlAGAcdDhU/2ZA,iv:UaCbaDLPFhyxVSe5CFDHc378DXkXZBw6xgl0AgP9UNc=,tag:9Xg0i7hX/Fz8geFGhhbX9A==,type:str]
    namespace: ENC[AES256_GCM,data:Cw9MkJfF7oizvhp7,iv:Bbk5xmw2LvP/pfbkvDcmfUdTaTpR3l21C2xJDur1nIw=,tag:nheOBYj+T+A61Spnwm9rgw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:OXnsU0qQhK+vBhX4dDVnYwi6wMHLuf+KUmxYz+0TN7xCLkLM/GWoqZ/A5fUl01atJkiAy/reCdZXy7osHTKIy0VPoJkE3r7K5ONh6rswkaI1P4dfdNww6LC2dtWW3kRQREG6rO6Tn8TZFr9xHLSmZefLYzaWXC9iqkJ20+lG5DU=,iv:9vYlPBuNP9xIIWNJVJrOZRXMOfbc+NGY2pK1l4gyLi4=,tag:j4C/O/4VFL2PFUysITQWxg==,type:str]
type: ENC[AES256_GCM,data:eod7Gzi557N5ZnjAy2W8ZuS3g5HtUeb8GrPmUWPF,iv:K+BqP8+n06YcbKSIzMcowU5xLGKrbj6BzXVSOCrylO0=,tag:gKAH9X9799BwQ/pNjQUggw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:085408454859:key/fb032225-ffb7-4c0d-87ef-2255683c423e
          created_at: "2021-06-10T17:51:02Z"
          enc: AQICAHjqPLBcv0Ebs4AY5bLXTacyU4GbG/ruI9706JEXIZhGlAFMhBEOWyGL9E5DAR8f3dWGAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8fA/Yy+QSodUwJadAgEQgDsx3xwiZp/hwzWeHXDgRMKTAW/v9a3PzKwt5eKWyWlHl/RukVPgBqGtyH26CZbF8s9kSaVgxXiHZyOsbw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-10T17:51:04Z"
    mac: ENC[AES256_GCM,data:sidj/Dy2otVvaJHa3sNX/BYviWGAnlUhAgXIxoPN6T4khqJe0nh0SsYHm88CcYEeL79/C1a3TOgaGU9JDCksZAE5dmXDRwDOODqAz91GuasVulCaio2huVwfTk3/QKDbQfQuPFsh75aNpf01GGFrlxSRj2/cD4aopSSpny6Waic=,iv:lKls0NQ+ETNa/3k7/D0d4C6XyNLVfQOU52A6jbqGYew=,tag:S0ULEuWwkzMTEmBXh/eoow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
