apiVersion: ENC[AES256_GCM,data:2nc=,iv:qv0TyLX3jJVF1LX0jZHfP2nYKifJUW8RLCCYsScqF3I=,tag:6auuVl8vNlSWBaabS1JBHA==,type:str]
kind: ENC[AES256_GCM,data:sdK/HJlL,iv:MmRWfmAQogZB8az3D5pzWNkAVfh24OEhNQYtyrQ/rfA=,tag:JqKJBqTLtpwbuPlUTRSaPg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XJs9AQrlAGAcdDhU/2ZA,iv:UaCbaDLPFhyxVSe5CFDHc378DXkXZBw6xgl0AgP9UNc=,tag:9Xg0i7hX/Fz8geFGhhbX9A==,type:str]
    namespace: ENC[AES256_GCM,data:Cw9MkJfF7oizvhp7,iv:Bbk5xmw2LvP/pfbkvDcmfUdTaTpR3l21C2xJDur1nIw=,tag:nheOBYj+T+A61Spnwm9rgw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:hbVWLu0mkI06xw7mtcNmVf/EkjP+Nnt7J16UrPuP9GexlNhOMAVaNEEt1zMAxlqkR4fu19cPKx+oxGH1wcPhfBK5iw8M9joX3HoFuBu4Rkb8c+30JdgxtHjiaVkDE2o1JicGj0wsNu8uTzeD2ScAGpJBxho82gQOpffRSErRrzI=,iv:Jp4uFnQLQIkHVmQvWUBlKvCn+JH6IaI/Db6g2OqjTy0=,tag:z3/+EuyHblAjz/Gp5OeMQQ==,type:str]
type: ENC[AES256_GCM,data:eod7Gzi557N5ZnjAy2W8ZuS3g5HtUeb8GrPmUWPF,iv:K+BqP8+n06YcbKSIzMcowU5xLGKrbj6BzXVSOCrylO0=,tag:gKAH9X9799BwQ/pNjQUggw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:085408454859:key/fb032225-ffb7-4c0d-87ef-2255683c423e
          created_at: "2021-06-10T17:51:02Z"
          enc: AQICAHjqPLBcv0Ebs4AY5bLXTacyU4GbG/ruI9706JEXIZhGlAFMhBEOWyGL9E5DAR8f3dWGAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8fA/Yy+QSodUwJadAgEQgDsx3xwiZp/hwzWeHXDgRMKTAW/v9a3PzKwt5eKWyWlHl/RukVPgBqGtyH26CZbF8s9kSaVgxXiHZyOsbw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-10T18:11:12Z"
    mac: ENC[AES256_GCM,data:T7dsu6bQI7SJLx46Zn+Av1BFfM2GAtXdDom2gD1Cjx29IkAISIx7DcSsumNY1zF6NksIefFXvAMhRDBACgyrXGWq7mvkbCsDIFigYxn8yEWYbHI9b0828BO/bJ7e8dVeCTnlz5HP7XweIAH3Z/pRZ4xqru7PwNDumjSmORmSe3I=,iv:ui95NF+2DSHgoFckRQghxHb9hvlI97hrx04aUXWrrk8=,tag:Mmgb6+iUx6YwW59fcIIUMw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
